stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "template..."

unit-test-job:
  stage: test
  script:
    - echo "template..."

lint-test-job:
  stage: test
  script:
    - echo "template..."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "template..."
