[package]
name = "arr-rs"
version = "0.0.0"
edition = "2021"
authors = [ "Paweł Walus <pawel.walus@protonmail.com>" ]
description = "arr-rs - rust arrays library"
keywords = ["arrays", "collections"]
homepage = "https://github.com/pw-order-of-devs"
repository = "https://github.com/pw-order-of-devs/arr-rs"
license = "MIT"

[lib]
name = "arr_rs"
path = "src/lib.rs"

[dependencies]
num-traits = "0.2"

[dev-dependencies]
rstest = "0.16"
