name: benchmark

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: true
      - name: benchmark
        run: cargo bench
      - name: Archive benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark
          path: target/criterion
