name: default build

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: rust:1.67-alpine
    steps:
      - name: build
        run: cargo build

  quality:
    runs-on: rust:1.67-alpine
    steps:
      - name: prepare
        run: |
          apk update
          apk add rustup
          rustup component add clippy

      - name: test
        run: cargo test

      - name: lint
        run: cargo clippy --all-targets --all-features -- -D warnings
